FROM webhippie/golang:latest AS build

ENV TRIVY_PATH github.com/aquasecurity/trivy
ENV TRIVY_REPO https://github.com/tboerger/trivy.git
ENV TRIVY_BRANCH env-variables

RUN git clone -b ${TRIVY_BRANCH} ${TRIVY_REPO} /srv/app/src/${TRIVY_PATH} && \
  cd /srv/app/src/${TRIVY_PATH} && \
  GO111MODULE=on go install -ldflags "-X main.version=$(git describe --tags --abbrev=0)" ./cmd/trivy

FROM webhippie/alpine:latest

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Trivy" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["/usr/bin/trivy"]

RUN apk update && \
  apk upgrade && \
  apk add git rpm && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/trivy /usr/bin/
